src/copick/models.py
The previous version would not allow the user to create new segmentations if the user_id and session_id had been used for any segmentations, specifically even if they had different names.
=> Check for existing segmentations with greater specificity

.github/workflows/test.yml, pyproject.toml, src/copick/impl/filesystem.py, tests/conftest.py, tests/docker-compose.yml, tests/seed_moto.sh, tests/seed_smb.sh, tests/seed_ssh.sh, tests/test_filesystem.py
- Adding in fixtures and infrastructure for S3-based tests. 
- Adding in fixtures and infrastructure for SSH-based tests.
- Adding in fixtures and infrastructure for SMB-based tests.
- `new_run` and `new_voxel_spacing` write files to make sure they exist on object stores
S3, SSH and SMB tests are only run on the ubuntu runner as it is the only one that has docker available.
Adressing #16
=> Add tests for S3-, SMB and SSH-based copick storage

pyproject.toml, tests/conftest.py, tests/test_filesystem.py
1. Adds requirement fsspec>=2024.6.0. This allows setting the filesystem parameter auto_mkdir=True as in the case of LocalFileSystem, which is a requirement for writing Zarr-files with /-dimension separators.
2. Adds requirement sshfs>=2024.6.0. This allows writing Zarr-files via sshfs.
Fixes #20 and #21 
Supercedes #24
=> Update fsspec requirement to allow writing Zarr via SMBFileSystem and sshfs

README.md, docs/quickstart.md
This fixes the example that is present at the end of the README and the quick-start document. That example doesn't currently work for me because zarr's [`Group.arrays()`](https://zarr.readthedocs.io/en/stable/api/hierarchy.html#zarr.hierarchy.Group.arrays) returns a generator/iterator.
This PR fixes the example to first materialize the arrays to the list, then index the first element. This approach is consistent with the tests.
Alternatively, I considered using `_, array = next(group.arrays())` to be more concise, but decided against it because it's less useful in the real world and may be less readable for the target audience. I also considered using a `tuple` and renaming `array` to `high_res_data`, but decided against both to keep consistency with other parts of the repo (e.g. the …
=> Fix README and quick-start example to be consistent with tests

README.md, docs/index.md, docs/snippets/cookiecutter.py, docs/snippets/solution_random_points.py, docs/tools.md, pyproject.toml, src/copick/models.py, tests/test_filesystem.py
Since the segmentations are no longer tied to a specific tomogram, checking if the voxel spacing exists is not necessary and prevents importing segmentations created on binned tomograms.
=> Remove check for voxel_spacing's existance when creating segmentation

src/copick/impl/filesystem.py
Adding random access broke the run query for symlinked runs. This PR fixes that and makes copick find symlinked runs.
=> bugfix: find symlinked runs.

pyproject.toml, src/copick/impl/cryoet_data_portal.py, src/copick/impl/filesystem.py, src/copick/models.py
Overrides `root.get_picks` and `root.get_segmentations` in order to allow querying against any scalar field of [cryoet_data_portal.Annotation](https://chanzuckerberg.github.io/cryoet-data-portal/python-api.html#annotation) and the list of author namees. 
The signature of `root.get_picks` changes to: 
```python 
def get_picks(
self,
object_name: str = None,
user_id: str = None,
session_id: str = None,
portal_meta_query: Dict[str, Any] = None,
portal_author_query: List[str] = None,
) -> List["CopickPicksCDP"]:
"""Get picks by name, user_id or session_id (or combinations). Portal metadata are compared for equality. Portal
authors are checked for inclusion in the full author list.
Args:
object_name: Name of the object to search for.
user_id: User ID to search for.
session_id: Session ID to …
```
=> Support querying against data portal annotation metadata to select picks/segmentation 

src/copick/models.py, tests/test_filesystem.py
Partially addressing #36 (no methods to store image arrays yet).
* Adds methods to get data directly in numpy arrays for tomograms, features, segmentations and picks
```python
tomogram.numpy(
zarr_group: str = "0",
x: slice = slice(None, None),
y: slice = slice(None, None),
z: slice = slice(None, None),
) -> np.ndarray:
```
```python
`segmentation.numpy(
zarr_group: str = "0",
x: slice = slice(None, None),
y: slice = slice(None, None),
z: slice = slice(None, None),
) -> np.ndarray:
```
```python
features.numpy(zarr_group: str = "0", slices: Tuple[slice, ...] = None,) -> np.ndarray
```
```python
picks.numpy() -> Tuple[np.ndarray, np.ndarray] #[N, 3] positions and [N, 4, 4] transforms
```
These apply slices to the underlying Zarr to avoid reading the whole array when trying to obtain …
=> Convenience methods for getting data as numpy arrays.

pyproject.toml, src/copick/impl/filesystem.py
sshfs uses 
```
{'size': 74,
'type': 'link',
'gid': 25018,
'uid': 5502,
'time': datetime.datetime(2024, 5, 28, 18, 34, 45),
'mtime': datetime.datetime(2024, 5, 28, 18, 34, 45),
'permissions': 41471,
'name': '...'
},
```
for links, which differs from localFS
```
{'size': 74,
'type': 'other',
'islink': True,
'gid': 25018,
'uid': 5502,
'time': datetime.datetime(2024, 5, 28, 18, 34, 45),
'mtime': datetime.datetime(2024, 5, 28, 18, 34, 45),
'permissions': 41471,
'name': '...'
},
```
This PR adds an additional test for that.
=> Fix finding symlinked runs when using SSHFS

pyproject.toml, src/copick/models.py, src/copick/util/ome.py, tests/test_filesystem.py
Adds additional reqs: 
- scikit-image
- psutil
This adds two methods for tomograms, objects, and segmentations: 
- `from_numpy` - overwrites the entire volume and computes multiscale on demand
- `set_region` - sets specfic subregions of the zarr from a numpy array
Also adds one method for features
- `set_region` - sets specfic subregions of the zarr from a numpy array
because the shape of feature maps is less defined no method is provided that would store multiscale information (@kephale I guess we could add one that at least creates proper OME-metadata for arbitrary arrays at one scale)
Also implements memory-size checks for all `numpy()`-methods implemented by #43.
closes #36
=> Adds convenience methods for storing numpy arrays as zarr. 

pyproject.toml, tests/seed_smb.sh
Switches the set up command for SMB tests from `docker-compose` (deprecated API) to `docker compose`.
=> Fix tests for SMB

src/copick/impl/cryoet_data_portal.py, src/copick/impl/filesystem.py
Replace use of `zip(..., strict=True)` with explicit assertion.
=> fix: Make cryoET data portal implementation compatible with python 3.9

src/copick/ops/open.py
Right now, copick requires a file on disk to be initialized, this PR allows parsing config strings.
=> Allow creating copick configs from json strings 

src/copick/__init__.py
Ensure `copick.from_string` is available with base module import
=> Add from_string to based module import

src/copick/__init__.py, src/copick/impl/cryoet_data_portal.py, src/copick/models.py
As multiple tomograms are now supported by the cryoET data portal, there needs to be a mechanism to query tomograms by processing type and processing software. This PR adds this feature. 
The old `get_tomogram` API returns only a single tomogram and is deprecated (but still functional). 
A new method `get_tomograms` is added that makes this call more consistent with other `get_*` calls in copick, returning a list of query results. In the case of cryoET data portal backend, the following API can be used for querying by portal metadata: 
```python
def get_tomograms(
self,
tomo_type: str,
portal_meta_query: Dict[str, Any] = None,
portal_author_query: List[str] = None,
) -> List["CopickTomogramCDP"]:
"""Get a tomogram by type. Portal metadata are compared for equality. Authors are compared …
```
=> feat: Allow querying copick tomograms with portal metadata

src/copick/__init__.py, src/copick/impl/cryoet_data_portal.py, src/copick/models.py
Annotations with shape_type "Point" do not have orientation information on the portal, so we shouldn't attempt to read it. 
Also fixes autogeneration of portal projects from dataset ids (was still relying on `go_id` field instead of `identifier`).
=> fix: Reading annotations with shape type "Point" from portal and portal project autogen.

pyproject.toml, src/copick/__init__.py
We need to pin below zarr 3 for now, or update zarr usage. Currently a fresh install of copick breaks with:
`ImportError: cannot import name 'FSStore' from 'zarr.storage'`
=> Pin copick below zarr v3

docs/snippets/root_list_objects_runs.py
root.objects.values() returns a syntax error, update the docs sample snippet to use the correct `CopickRoot` property.
=> update docs snippet

pyproject.toml, src/copick/util/portal.py, tests/conftest.py
Don't traverse GraphQL entities in the loop.
=> Increase speed of pickable object creation for portal projects. 

pyproject.toml, src/copick/impl/cryoet_data_portal.py, tests/conftest.py
Properly cache picks files from the cryoET data portal and avoid query duplication.
=> Speed up cryoET data portal picks queries. 

src/copick/__init__.py, src/copick/impl/cryoet_data_portal.py
Build the names as: 
```python
name = f"{reconstruction_method}-{processing_method}"
if processing_tool:
name += f"-{processing_tool}"
if ctf_status:
name += f"-{ctf_status}"
```
to make finding specific tomo types easier. 
Example:
```python
import copick
project = copick.from_czcdp_datasets([10446], "/tmp/testoverlay")
project.get_run("17803").voxel_spacings[0].tomograms
```
out:
```
[CopickTomogram(tomo_type=wbp-denoised-denoiset-ctfdeconv, len(features)=None) at 0x16c616fb0,
CopickTomogram(tomo_type=wbp-filtered-ctfdeconv, len(features)=None) at 0x16c6172b0]
```
=> Improve tomogram names for tomos from the cryoET data portal.

src/copick/__init__.py, src/copick/impl/cryoet_data_portal.py
This PR fixes a typo in the `cryoet_data_portal.py` file where 'tomo_typxe' was incorrectly used instead of 'tomo_type' when creating tomogram metadata from a portal source.
The typo was in `CopickTomogramMetaCDP.from_portal` method, line 476.
Fix: Changed 'tomo_typxe=name' to 'tomo_type=name'.
=> Fix typo in CryoET Data Portal tomogram metadata

src/copick/impl/cryoet_data_portal.py, src/copick/impl/filesystem.py, src/copick/impl/overlay.py, src/copick/models.py, tests/test_delete_overwrite.py
This PR adds deletion and overwrite logic for: 
- `CopickRun`
- `CopickVoxelSpacing`
- `CopickTomogram`
- `CopickFeatures`
- `CopickPicks`
- `CopickMesh`
- `CopickSegmentation`
##Deletion Features
Added methods to delete various entities from both memory and filesystem:
- Run deletion  (`CopickRun.delete`)
- Tomogram deletion (`CopickTomogram.delete`)
- Feature deletion (`CopickFeatures.delete`)
- Picks deletion (`CopickPicks.delete`)
- Mesh deletion (`CopickMesh.delete`)
- Segmentation deletion (`CopickSegmentation.delete`)
Added cascading batch deletion methods for collections:
- `CopickRoot`
- `CopickRoot.delete_run`
- `CopickRun`
- `CopickRun.delete_voxel_spacings` with filtering by `voxel_spacing`
- `CopickRun.delete_picks` with filtering by `object_name`, `user_id` and `session_id` …
=> Add deletion and overwriting logic for copick entities

.github/workflows/build-and-deploy-docs.yml
The docs workflow was broken because of a known issue in pip 25.1.1. This PR migrates it to use `uv pip`.
=> chore: Migrate docs workflow to uv pip

docs/cli.md, src/copick/cli/add.py, src/copick/impl/cryoet_data_portal.py, src/copick/impl/filesystem.py, src/copick/impl/overlay.py, src/copick/models.py, src/copick/ops/add.py, src/copick/util/formats.py, tests/test_cli.py, tests/test_filesystem.py, tests/test_object_models.py
This PR introduces the ability to add objects to copick projects. 
Using the model API, you can add a copick object and store the resulting config using `project.new_object` and `project.save_config`.
```python
def new_object(
self,
name: str,
is_particle: bool,
label: Optional[int] = None,
color: Optional[Tuple[int, int, int, int]] = None,
emdb_id: Optional[str] = None,
pdb_id: Optional[str] = None,
identifier: Optional[str] = None,
map_threshold: Optional[float] = None,
radius: Optional[float] = None,
exist_ok: bool = False,
) -> "CopickObject":
"""Create a new pickable object and add it to the configuration.
Args:
name: Name of the object.
is_particle: Whether this object should be represented by points (True) or segmentation masks (False).
label: Numeric label/id for the object. If …
```
=> feat: Add ability to add objects.

src/copick/util/ome.py, tests/test_cli.py
Units where incorrectly stored in the transformation metadata, instead of the axes metadata. 
Also updated `get_voxel_size_from_zarr` to read the voxelsize correctly.
=> fix: Store OME metadata correctly.

README.md, docs/quickstart.md, pyproject.toml, uv.lock
Using copick with data stored on a remote server with SSH access is a core part of the workflow now. To avoid confusion when users are installing for the first time (and potentially forget the extra dependencies), `sshfs` is moved to the core dependencies. The docs are updated to reflect this.
=> fix: Make sshfs a core dependency and update docs.

src/copick/cli/add.py
CLI tools for adding tomograms were failing because the `overwrite` option was not being passed into `exist_ok`, but only the zarr `overwrite` parameter.
=> fix: Fix overwrite option on CLI

README.md, docs/quickstart.md
`pip==25.2` fixed the resolution errors, we can now recommend using pip for installation again.
=> docs: Update docs to reflect fix in pip==25.2
